on:
  push:
    branches: [main]

concurrency:
  group: deploy
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: nix
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - run: colmena apply --on @deploy-on-merge
