name: Deploy Stacks

on:
  push:
    branches: [main]
    paths:
      - "stacks/cube/arr-lxc/arr/**"

jobs:
  deploy-arr:
    runs-on: ubuntu-latest
    steps:
      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Trigger Dockhand webhook
        run: curl -sfk "https://proxy.tail1d49f8.ts.net/api/git/stacks/6/webhook?secret=${{ secrets.DOCKHAND_WEBHOOK_SECRET }}"
